SELECT DISTINCT PRODUCT_NAME,PRODUCT_ID, PRICE,
DECODE(PRODUCT_GENDER,'M','남성','FM','여성') AS PRODUCT_GENDER, STOCK, 
DECODE(CATEGORY,'1','상의','2','하의','3','치마','4','원피스','5','아우터') AS CATEGORY
FROM PRODUCT
ORDER BY TO_NUMBER(2);



SELECT  PRODUCT_ID, PRODUCT_NAME, PRICE, PRODUCT_SIZE,
         DECODE(PRODUCT_GENDER,'M','남성','FM','여성') AS PRODUCT_GENDER, STOCK,
         DECODE(CATEGORY,'1','상의','2','하의','3','치마','4','원피스','5','아우터') AS CATEGORY
         FROM PRODUCT
         WHERE PRODUCT_NAME IN '플리스 셔츠 자켓' OR PRODUCT_NAME LIKE '%히든밴딩%';
         
         
         
SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, PRODUCT_SIZE, 
DECODE(PRODUCT_GENDER,'M','남성','FM','여성') AS PRODUCT_GENDER, 
STOCK, DECODE(CATEGORY,'1','상의','2','하의','3','치마','4','원피스','5','아우터') AS CATEGORY  
FROM PRODUCT  
WHERE PRODUCT_GENDER = :1;

SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, PRODUCT_SIZE;

qqkrtkals!1
select * from member;




SELECT PRODUCT_ID, PRODUCT_NAME, PRICE, PRODUCT_SIZE,
DECODE(PRODUCT_GENDER,'M','남성','FM','여성') AS PRODUCT_GENDER, STOCK, 
DECODE(CATEGORY,'1','상의','2','하의','3','치마','4','원피스','5','아우터') AS CATEGORY
FROM PRODUCT
ORDER BY TO_NUMBER(3);




INSERT INTO BUY (ID, PRODUCT_ID, MEMBER_ID)
VALUES (SEQ_BUY.nextval, '1', 'akdrhtn2');


SELECT * FROM MANAGER;
DROP TABLE BUY;

select * from product;
SELECT * FROM MEMBER;


SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_SIZE, TO_DATE(B.B_DATE, 'YYYY-MM-DD') B_DATE FROM PRODUCT P, MEMBER M, BUY B
WHERE P.PRODUCT_ID = B.PRODUCT_ID
AND B.MEMBER_ID = M.ID
AND B.MEMBER_ID = 'akdrhtn2';

select * from member;
select * from manager;
insert into values




