CREATE TABLE MEMBER(
    ID VARCHAR2(20) CONSTRAINT USER_PK PRIMARY KEY,
    PASSWORD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    BIRTH DATE DEFAULT SYSDATE,
    GENDER NUMBER NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(20) NOT NULL,
    POINT VARCHAR2(20) NOT NULL,
    RANK VARCHAR2(20) NOT NULL
);

CREATE TABLE PRODUCT (
    PRODUCT_ID VARCHAR2(20) NOT NULL CONSTRAINT PRODUCT_PK PRIMARY KEY 
    , PRODUCT_NAME VARCHAR2(20) NOT NULL 
    , PRICE NUMBER NOT NULL 
    , PRODUCT_SIZE NUMBER NOT NULL 
    , STOCK NUMBER NOT NULL 
);


CREATE TABLE PRODUCT_REVIEWS (
    ID NUMBER CONSTRAINT REVIEWS_PK PRIMARY KEY,
    PRO_ID VARCHAR2(20) CONSTRAINT PRODUCT_FK
    REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    CONTENT VARCHAR2(100),
    WRITER VARCHAR2(20) CONSTRAINT PRODUCT_FK2
    REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE TABLE BUY (
    ID NUMBER NOT NULL CONSTRAINT BUY_PK PRIMARY KEY
    , P_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER (ID)
    , U_ID VARCHAR2(20) NOT NULL REFERENCES MEMBER (ID)
);
DROP TABLE MANAGER;
CREATE TABLE MANAGER (
    ID VARCHAR2(20) NOT NULL CONSTRAINT MANAGER_PK PRIMARY KEY 
    , PASSWORD VARCHAR2(20) NOT NULL 
    , NAME VARCHAR2(20) NOT NULL 
    , RANK VARCHAR(20) NOT NULL
);

--추가된 필드 (PRODUCT : 성별, 사이즈, 종류)
ALTER TABLE PRODUCT ADD PRODUCT_GENDER VARCHAR2(20) NOT NULL;

ALTER TABLE PRODUCT ADD PRODUCT_SIZE VARCHAR2(20) NOT NULL;

ALTER TABLE PRODUCT ADD CATEGORY VARCHAR2(20) NOT NULL;
-- 멤버(카드번호, 카드 지불)
ALTER TABLE MEMBER ADD CARD_NUMBER VARCHAR2(20) NOT NULL;
ALTER TABLE MEMBER ADD CARD_PAYMENT VARCHAR2(20) NOT NULL;

-- 관리자(전화번호 추가)
ALTER TABLE MANAGER ADD PHONE VARCHAR2(20) NOT NULL;

-- 카드 테이블 추가
CREATE TABLE CARD(
    ID VARCHAR2(20) CONSTRAINT CARD_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) CONSTRAINT CARD_FK
    REFERENCES MEMBER(ID) ON DELETE CASCADE,
    BALANCE VARCHAR2(20) NOT NULL
);

-- 장바구니 테이블 추가 
CREATE TABLE CART(
    SB_ID NUMBER CONSTRAINT SB_PK PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) CONSTRAINT CART_FK
    REFERENCES MEMBER(ID) ON DELETE CASCADE,
    PRODUCT_ID VARCHAR2(20) CONSTRAINT CART_FK2
    REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    PRODUCT_NAME VARCHAR2(100)
);
-- 상품평 시퀀스 생성
CREATE SEQUENCE SEQ_REVIEW
    START WITH 1
    INCREMENT BY 1
    NOCACHE;


--구매 테이블에 가격 NUMBER 추가
ALTER TABLE BUY ADD BUY_PRICE NUMBER NOT NULL;

ALTER TABLE BUY DROP BUY_PRICE;


SELECT *
FROM BUY B
JOIN PRODUCT P 
ON B.PRODUCT_ID = P.PRODUCT_ID;